### PR TITLE
Solved  [Feature]: Move to the top of the page with every new search. #672

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
This pull request resolves #XXX

 - [x] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [x] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [x] What I'm implementing was assigned to me and is an [approved issue](https://github.com/movie-web/movie-web/issues?q=is%3Aopen+is%3Aissue+label%3Aapproved). For reference, please take a look at our [GitHub projects](https://github.com/movie-web/movie-web/projects).
 - [x] I have tested all of my changes.

### CODE REVIEW

**Comment by JipFr** [comment]
I don't really agree with this. I feel like even if the issue was approved, which it hasn't been, it shouldn't scroll past the title so you can see the top results.

**Comment by Ayushmaanagarwal1211** [comment]
> I don't really agree with this. I feel like even if the issue was approved, which it hasn't been, it shouldn't scroll past the title so you can see the top results.

so if i add a feature is that when user unfocused from search bar then it moves to the top otherwise not .

**Comment by JipFr** [comment]
IMO when something is searched it should scroll to the title, but I want to hear Jvs' thoughts on this before anything else is done. This discussion should take place in the issue, not this PR (imo)

**Comment by tan-ahmed** [comment]
this is a good UX thing

**Comment by zaim-abbasi** [comment]
Or maybe we could  scroll to a position some pixels above the first search result image, subtracting a specific number of pixels from the offsetTop value of the first search result. like this:

const firstResult = document.getElementById('firstSearchResult');

  if (firstResult) {

    const offsetAboveResult = 20; // 20 pixels above the first search result

    // Calculate the offsetTop
    const offsetTop = firstResult.offsetTop;

    window.scrollTo({
      top: offsetTop - offsetAboveResult,
      left: 0,
      behavior: 'smooth',
    });
  }

**Comment by mrjvs** [comment]
As a heads up, I won't have the time to review properly until after new years.

**Comment by mrjvs** [comment]
movie-web currently already goes to top of the page when searching, there is no need for this PR.
additionally, the issue was not approved to begin with.

**Pull request closed without merging**
