### PR TITLE
The Next Episode

### LINKED ISSUE #140: [Feature]: Autoplay next episode
### What feature do you want to add?

when reaching end of episode, automatically move to next episode of series

### Why do you want to have this feature?

makes it more fun to binge watch

### Anything other details to share?

_No response_

### PR DESCRIPTION
**Pull request by frost768**
As Dr.Dre said "Take a seat, Hope you ready for the next episode "
Partially fix #140 
To show the next episode from the next season at the last episode of the current season should fetch that first
Preview:
ezgif com-video-to-gif

### CODE REVIEW

**Comment by zisra** [comment]
Why partial lol. Also kudos to you for all these great PRs

**Comment by frost768** [comment]
> As Dr.Dre said "Take a seat, Hope you ready for the next episode " Partially fix #140 To show the next episode from the next season at the last episode of the current season should fetch that first



> Why partial lol. Also kudos to you for all these great PRs
because it won't show the next season's episode

**Comment by Tazi0** [comment]
Hey man, just came across this PR! Might I suggest changing?
* Might the colors fit in with the theme of the site? Just like the "watermark" on the top right of the screen? 
* It also would be nice if it automatically could go to the next episode once it filled in.
* Pausing the movie would still continue filling up the bar, is this a bug?

**Comment by frost768** [comment]
> Hey man, just came across this PR! Might I suggest changing?
> 
>     * Might the colors fit in with the theme of the site? Just like the "watermark" on the top right of the screen?
> 
>     * It also would be nice if it automatically could go to the next episode once it filled in.
> 
>     * Pausing the movie would still continue filling up the bar, is this a bug?

i think the colors should stay black and white. with these colors contrast is max
it does go to next episode after it fills
yes that shouldnt be happening

**Comment by zisra** [comment]
Are you planning to incorporate the next season?

**Comment by binaryoverload** [comment]
As mentioned in the Discord, we would like one of the core maintainers to have a proper look at this later.

Thanks for your effort, and I'm sorry we won't be using this PR.

**Pull request closed without merging**
