### PR TITLE
Added .nvmrc file

### LINKED ISSUE #682: [Bug]: failed to load config from [movie-web-directory]/vite.config.mts
### What happened?

Whenever I run pnpm run dev (after I ran pnpm install), I get this error:

> failed to load config from /Users/[redacted]/Sites/movie-web/vite.config.mts
>error during build:
>TypeError: Cannot redefine property: File
>    at Function.defineProperty (<anonymous>)
>     at Object.<anonymous> (/Users/[redacted]/Sites/movie-> web/node_modules/.pnpm/@babel+core@7.23.6/node_modules/@babel/core/lib/index.js:7:8)
>     at Module._compile (node:internal/modules/cjs/loader:1241:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
>     at Module.load (node:internal/modules/cjs/loader:1091:32)
 >    at Module._load (node:internal/modules/cjs/loader:938:12)
 >    at Module.require (node:internal/modules/cjs/loader:1115:19)
 >    at require (node:internal/modules/helpers:130:18)
 >    at Object.<anonymous> (/Users/[redacted]/Sites/movie-> > web/node_modules/.pnpm/@babel+core@7.23.6/node_modules/@babel/core/lib/config/helpers/config-api.js:16:14)
>     at Module._compile (node:internal/modules/cjs/loader:1241:14)
 > ELIFECYCLE  Command failed with exit code 1.

### What browsers are you seeing the problem on?

Other (tell us in input box below)

### Steps to reproduce?

1. git clone the movie-web
2. cd into the directory
3. Run pnpm install
4. Run pnpm run dev

### Other relevant information

_No response_

### PR DESCRIPTION
**Pull request by usman1100**
**Title:** Add .nvmrc configuration file

**Description:**
This PR introduces a new file, `.nvmrc`, to the project. This file specifies the Node.js version to be used when working on the project. The inclusion of this file has several benefits:

1. **Consistent Development Environment:** With a defined Node.js version, all contributors will use the same Node version when working on the project. This ensures a consistent development environment and reduces the likelihood of compatibility issues.

2. **Avoid Unexpected Behavior:** In the past like [here](https://github.com/movie-web/movie-web/issues/682), we've observed unexpected behavior caused by differences in Node.js versions. By explicitly specifying Node version 20 in the `.nvmrc` file, we aim to mitigate potential issues and create a more stable development environment.

**How to Use:**
1. Make sure you have Node Version Manager (NVM) installed. If not, you can install it by following the instructions [here](https://github.com/nvm-sh/nvm).
2. After installing NVM, run the following command in the project directory:
   ```
   nvm use
   ```
   This will automatically switch your Node.js version to the one specified in the `.nvmrc` file (Node version 20 in this case).

3. Ensure that you have the correct Node version active by running:
   ```
   node -v
   ```

By adopting this approach, we aim to streamline the development process and create a more reliable and consistent environment for all contributors. Feel free to reach out if you have any questions or concerns regarding this change.

This pull request resolves #682

 - [X] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [X] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [X] What I'm implementing was assigned to me and is an [approved issue](https://github.com/movie-web/movie-web/issues?q=is%3Aopen+is%3Aissue+label%3Aapproved). For reference, please take a look at our [GitHub projects](https://github.com/movie-web/movie-web/projects).
 - [X] I have tested all of my changes.

### CODE REVIEW

**Comment by JipFr** [comment]
Did yoh make ChatGPT write this? Be honest, now.

**Comment by usman1100** [comment]
> Did yoh make ChatGPT write this? Be honest, now.

Yeah, English isn't my native language so I use LLMs to sort of "validate" my descriptions. Otherwise the description would've less than "readable" :)

**Comment by binaryoverload** [comment]
We don't need yet another config file

We document that you need node 20 - NVM is simple enough to use by itself

**Comment by usman1100** [comment]
> We don't need yet another config file
> 
> We document that you need node 20 - NVM is simple enough to use by itself

It's better to have a hard coded config file, not only for the users, but it can also be configured to be read by deployment platforms like Vercel or Netlify.

This config can remove some manual steps in the app deployment and management workflow, even though the advantages might not be visible right now, we'll need it in the future when dependencies grow.

And the users don't need to go through the Readme just to figure out what version of Node they should be using, then can just run a command. And some users like myself who work in a lot of node projects simul

**Comment by usman1100** [comment]
> We don't need yet another config file
> 
> We document that you need node 20 - NVM is simple enough to use by itself

It's better to have a hard coded config file, not only for the users, but it can also be configured to be read by deployment platforms like Vercel or Netlify.

This config can remove some manual steps in the app deployment and management workflow, even though the advantages might not be visible right now, we'll need it in the future when dependencies grow.

And the users don't need to go through the Readme just to figure out what version of Node they should be using, then can just run a command. And some users like myself who work in a lot of node projects simultaneously, have bash/zsh scripts set up to automatically switch to the node version of the .nvmrc file (if provided).

I strongly suggest we add this config to the project.

**Pull request closed without merging**
