### PR TITLE
Backdrop blur for the navigation buttons

### LINKED ISSUE #801: [Feature]: Adding backdrop blur for the navigation buttons
### What feature do you want to add?

Just add backdrop filter with blur value to improve the interface on the navigation while scrolling

### Why do you want to have this feature?

Because I don't think users feel comfortable with the zero opacity on the buttons while they scrolling the page

### Anything other details to share?

_No response_

### PR DESCRIPTION
**Pull request by Pyr33x**
This pull request resolves #801

 - [x] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [x] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [ ] What I'm implementing was assigned to me and is an [approved issue](https://github.com/movie-web/movie-web/issues?q=is%3Aopen+is%3Aissue+label%3Aapproved). For reference, please take a look at our [GitHub projects](https://github.com/movie-web/movie-web/projects).
 - [x] I have tested all of my changes.

Screenshot 2024-01-21 213855

> to this: 
Screenshot 2024-01-21 213827

### CODE REVIEW

**Comment by castdrian** [comment]
Screenshot_20240122_000036_Samsung Internet

**Comment by MemeCornucopia** [comment]
I don't think anyone assigned it to you

**Comment by Pyr33x** [comment]
I felt like something is wrong, so that's why

**Comment by MemeCornucopia** [comment]
You checked boxed that you were assigned it

**Comment by JipFr** [comment]
That is _not_ how that works.

**Comment by Pyr33x** [comment]
so I gotta close the pr? :(

**Comment by thehairy** [comment]
Your issue wasn't even approved yet, so, probably?
And I disagree with your issue/pr anyway. :P

**Comment by MemeCornucopia** [comment]
Never even said you had to close it? JUST UNCHECK THE BOX THAT SAYS IT WAS ASSIGNED TO YOU.

**Review by binaryoverload — APPROVED** [review]

**Pull request merged**
