### PR TITLE
Drop subtitle file

### PR DESCRIPTION
**Pull request by zisra**
Screen Recording 2023-05-22 at 6 06 45 PM

- **Allow dropping subtitle files, for better UX. This makes it very easier for me**
- Pressing `esc` closes all popouts. This is pretty much standard

### CODE REVIEW

**Review by thehairy — APPROVED** [review]
Looks good, but you might as well complete the other translations too, deepl should be quite accurate for this.

**Comment by kach17** [comment]
Can there be some hint in UI that drag and drop is available?

**Comment by zisra** [comment]
I would love to, just can't find  a way to

**Comment by JamesHawkinss** [comment]
> I would love to, just can't find a way to

@mrjvs ux needed

**Comment by binaryoverload** [comment]
Thanks for your PR, but as there isn't an issue for this, we will close this for now. 

If an issue is accepted for this feature, you can ask to be assigned to it.

**Pull request closed without merging**
