### PR TITLE
Add Apple touch startup images

### LINKED ISSUE #594: [Feature]: iOS(PWA) Splash Screen
### What feature do you want to add?

iOS Pwa Splash Screen

### Why do you want to have this feature?

Currently when you open the app it's just blank which it's kinda annoying.

### Anything other details to share?

I couldn't really wait for this to be approved and then work on it so i made a pr for if you guys do want it if not just close the issue and pr it's no problem. PR: #593

### PR DESCRIPTION
**Pull request by Jecta**
This pull request resolves #594 

 - [x] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 -  [x] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [x] What I'm implementing was assigned to me and is an [approved issue](https://github.com/movie-web/movie-web/issues?q=is%3Aopen+is%3Aissue+label%3Aapproved). For reference, please take a look at our [GitHub projects](https://github.com/movie-web/movie-web/projects).
 - [x] I have tested all of my changes.

### CODE REVIEW

**Review by binaryoverload — CHANGES_REQUESTED** [review]
It seems that whatever generator has been used to make these images is a bit out of date, it does not include the iPhone 15 for example which would be:

```html
<link rel="apple-touch-startup-image" media="screen and (device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" href="INSERTME">
```

Could you have a look to see if you can get a complete list of up to date devices? https://progressier.com/pwa-icons-and-ios-splash-screen-generator seems to be a generator which supports iPhone 15

**Comment by binaryoverload** [comment]
I wonder if we can use `https://github.com/GoogleChromeLabs/pwacompat` to dynamically generate the slash screens so we don't have to keep them up to date

**Comment by Jecta** [comment]
That's interesting, here's a temporary fix.

**Comment by binaryoverload** [comment]
@Jecta do you have an Apple device that you test this on? The reason I ask is that if you do I'd like to try out the [pwacompat](https://github.com/GoogleChromeLabs/pwacompat) library and see if that works at all

**Comment by Jecta** [comment]
I have tested the demo on my iPhone now and i see that it works, however i'm personally not avaliable to intergrate it. Do you think pwacompat is a better option? You can always migrate to use it later, the no splash screen on PWA is pretty annoying for now.

**Comment by mrjvs** [comment]
I think this is good for a first iteration, however I would like generate these images on demand for the next version.

**Comment by mrjvs** [comment]
@binaryoverload could you rereview?

**Review by binaryoverload — APPROVED** [review]

**Pull request merged**
