### PR TITLE
Support for HLS audio tracks

### LINKED ISSUE #423: [Feature]: Change audio track
### What feature do you want to add?

Superstream's mp4 files have multiple audio tracks on them you can choose from. 

### Why do you want to have this feature?

I want to be able to switch the language. Often times it plays a language I don't know when English is available. 

### Anything other details to share?

I'm using the video player IINA and got this for a movie, it would be nice to have a audio selector 
image

Unfortunately there is no official API lets you do this but hopefully there is some kind of hack to bypass this. There's https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/videoTracks but that does not let you do it.

### PR DESCRIPTION
**Pull request by JorrinKievit**
This pull request resolves #423 

Ridomovies supplies different audio tracks for certain shows. ex: https://mw.lonelil.ru/media/tmdb-tv-112836-money-heist-korea-joint-economic-area/168159/2501960

This doesn't support MP4, but in my opinion that's a bit out of scope.
It now shows the Audio menu when there is 1 or more. But maybe it's better to only show the menu if there's more than 1? Let me know 😄 

image
image

 - [x] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [x] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [x] What I'm implementing was assigned to me and is an [approved issue](https://github.com/movie-web/movie-web/issues?q=is%3Aopen+is%3Aissue+label%3Aapproved). For reference, please take a look at our [GitHub projects](https://github.com/movie-web/movie-web/projects).
 - [x] I have tested all of my changes.

### CODE REVIEW

**Comment by TecEash1** [comment]
I am not sure how this would look or be implemented… but if there was a flag icon like the subtitles it *may* look a bit better. Not sure though just an idea I thought I’d share.

**Comment by JorrinKievit** [comment]
> I am not sure how this would look or be implemented… but if there was a flag icon like the subtitles it _may_ look a bit better. Not sure though just an idea I thought I’d share.

Haha yes I said the same thing internally, will see if I can make that work consistently

**Comment by quote-therizzler** [comment]
wait omg fr

**Comment by JorrinKievit** [comment]
Added the flags, should look a lot better ;D

**Comment by TecEash1** [comment]
Awesome! 💯

**Review by binaryoverload — APPROVED** [review]

**Comment by JorrinKievit** [comment]
> May I ask why MP4 is out of scope?

Because its a lot of work and no provider offers multiple languages in mp4 format

**Pull request merged**
