### PR TITLE
Added Galician Language (gal)

### PR DESCRIPTION
**Pull request by n1cklim**
Galician language is spoken in Spain, and it's an official language in Spain.

I suggest adding Galician as it would add richness to this application.
In addition, people who speak Galician can better understand the interface.

It has similarities with Spanish.
Anyway, I am a native Spanish and Galician speaker, and I will have to do another pull request to fix errors with the Spanish language .json.

This pull request resolves #XXX

 - [x] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [x] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [ ] What I'm implementing was assigned to me and is an [approved issue](https://github.com/movie-web/movie-web/issues?q=is%3Aopen+is%3Aissue+label%3Aapproved). For reference, please take a look at our [GitHub projects](https://github.com/movie-web/movie-web/projects).
 - [ ] I have tested all of my changes.

### CODE REVIEW

**Comment by binaryoverload** [comment]
Please use our translation platform Weblate: https://weblate.movie-web.app

**Comment by n1cklim** [comment]
Hey @binaryoverload !
If I want to add another language (Galician in this case), what should I do?

**Comment by mrjvs** [comment]
Read the contribution guidelines, it contains all information you. including how to add a language

**Comment by n1cklim** [comment]
Where are those? In README?

**Comment by mrjvs** [comment]
> Where are those? In README?

You said you read them

**Comment by binaryoverload** [comment]
image

**Pull request closed without merging**
