### PR TITLE
Update and Fix GitHub Actions

### LINKED ISSUE #627: [Feature]: Add ARM support for Docker images
### What feature do you want to add?

Publish a new Docker image for Arm processors to support development on Apple chips

### Why do you want to have this feature?

I am trying to launch the proxy locally. However i can't run the latest image (`ghcr.io/movie-web/simple-proxy:2.1.0`).

### Anything other details to share?

 Would be nice to be able to pull the image instead of building it locally

### LINKED ISSUE #746: [Bug]: Publish Workflow fails due to wrong lockfile
### What happened?

The PR #722 which should publish a Docker Image for the frontend doesn't work, as the Deploying workflow [always fails](https://github.com/movie-web/movie-web/actions/runs/7434046497). It seems that there is something wrong with the [pnpm-lock.yaml](https://github.com/movie-web/movie-web/blob/dev/pnpm-lock.yaml).

### PR DESCRIPTION
**Pull request by binaryoverload**
This pull request is for #627 (Sorry @weeryan17 - Thought I might as well as it's one line) and resolves #746 

- Update all action versions
- Update Node version to 20
- Add caching for GitHub build

### CODE REVIEW

**Comment by weeryan17** [comment]
Trying to build the docker image on my pi seams pnpm doesn't like us
https://pastebin.com/EuhF02MN
Haven't tested the workflow yet

**Comment by weeryan17** [comment]
Looks like we just need to add an override https://github.com/vitejs/vite/issues/15122

**Review by mrjvs — CHANGES_REQUESTED** [review]
I think its wise to add docker build to the testing workflow. Just so we don't miss another broken docker build.

**Review by mrjvs — APPROVED** [review]

**Comment by mrjvs** [comment]
looks, good but lets wait for weeryan17 to test it for arm before we merge

**Comment by weeryan17** [comment]
I have tested it, it's working.

**Pull request merged**
