### PR TITLE
Watch party

### LINKED ISSUE #109: [Feature]: Watch together
### What feature do you want to add?

The ability to watch together with other friends, sharing a single movie at the same time

### Why do you want to have this feature?

Cool collaboration

### Anything other details to share?

https://github.com/lesmana/webrtc-without-signaling-server

### PR DESCRIPTION
**Pull request by frost768**
P2PT node package is using simple-peer and it is using wrong URL spec for STUN server url causing Chrome to deny it
See [here](https://github.com/twilio/twilio-video.js/issues/1934)
That's why I downloaded it from [p2pt  github repo](https://github.com/subins2000/p2pt) and changed Twilio STUN url

Note: auto play is not allowed by the browsers until user interacts with the video element. this prevents playing the video when opened from the shared url by the host

Fix #109 

Preview [movie-web-git-watch-party-frost768.vercel.app](https://movie-web-git-watch-party-frost768.vercel.app/#/dev/video)

### CODE REVIEW

**Comment by zisra** [comment]
How is this different from the 2 branches in this repo?

**Comment by mrjvs** [comment]
> How is this different from the 2 branches in this repo?

this one works :P (somewhat)
itll still need work but its a great start

**Comment by frost768** [comment]
> How is this different from the 2 branches in this repo?

One was using only RTC which didnt have a signalling server, the other was kinda ready but couldnt make it work on my machine.
randombytes package was using `global` instead of `globalThis` which made it unusable on browsers

**Comment by mrjvs** [comment]
As it's been active for a while, gonna close this. especially since we enter a feature freeze for v4.
We can revisit this idea and PR after the freeze.

**Pull request closed without merging**
