### PR TITLE
Subtitle rendering feature added

### LINKED ISSUE #137: [Feature]: Subtitle renderer
### What feature do you want to add?

browser rendered VTT's are bad, we should make our own renderer.
it should have settings to set the offset

### Why do you want to have this feature?

Browsers dont allow us to position captions where we want them.

### Anything other details to share?
do after v3 release

### PR DESCRIPTION
**Pull request by frost768**
Resolves #137 
- Add settings context which includes delay and styling options for subtitles
- Add popout with controls that look like from the 90's for subtitle settings
- Add types for node-webvtt since the library doesn't have types for TypeScript 

a

### CODE REVIEW

**Comment by frost768** [comment]
>   * I'll get you a design for how the popout should look, if its too difficult then we can also just merge it and let the movie-web team do the rest, if you wish of course.
I may try it but it can take some time

**Comment by mrjvs** [comment]
design is ready:

**Comment by frost768** [comment]
b

**Comment by mrjvs** [comment]
Made some changes myself. just some UX details.
I normally dont do that, but done it this time to save time.

anyways, looks great now. thanks a lot for this much requested feature.

**Review by mrjvs — APPROVED** [review]

**Comment by zisra** [comment]
Screenshot 2023-03-19 at 7 39 39 PM
This looks weird to me

**Pull request merged**
